package vista;

import JASPER.ReportGenerator;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class VstReportUser extends javax.swing.JPanel {

    /**
     * Creates new form VstReportUser
     */
    public VstReportUser() {
        initComponents();
    }

    public void rpActiveUsers() {
        try {
            JasperPrint reporteLleno = ReportGenerator.rpActiveUsers();
            //JasperExportManager.exportReportToPdfFile(reporteLleno, "reporte.pdf");
            JasperViewer viewer = new JasperViewer(reporteLleno);
            viewer.setVisible(true);
        } catch (Exception e) {
        }
    }

    public void rpInactiveUsers() {
        try {
            JasperPrint reporteLleno = ReportGenerator.rpIactiveUsers();
            //JasperExportManager.exportReportToPdfFile(reporteLleno, "reporte.pdf");
            JasperViewer viewer = new JasperViewer(reporteLleno);
            viewer.setVisible(true);
        } catch (Exception e) {
        }
    }

    public void rpEmployeeUsers() {
        try {
            JasperPrint reporteLleno = ReportGenerator.rpEmployeeUsers();
            //JasperExportManager.exportReportToPdfFile(reporteLleno, "reporte.pdf");
            JasperViewer viewer = new JasperViewer(reporteLleno);
            viewer.setVisible(true);
        } catch (Exception e) {
        }
    }

    public void rpClientUsers() {
        try {
            JasperPrint reporteLleno = ReportGenerator.rpClientUsers();
            //JasperExportManager.exportReportToPdfFile(reporteLleno, "reporte.pdf");
            JasperViewer viewer = new JasperViewer(reporteLleno);
            viewer.setVisible(true);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        btnBuscarTercero = new javax.swing.JButton();
        btnUsuariosActivos = new javax.swing.JButton();
        btnUsuariosEliminados = new javax.swing.JButton();
        btnEmpleadosRegistrados = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setToolTipText("");
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsuarios.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("Usuarios");
        lblUsuarios.setToolTipText("");
        lblUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblUsuarios.setPreferredSize(new java.awt.Dimension(200, 50));

        btnBuscarTercero.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBuscarTercero.setText("Terceros");
        btnBuscarTercero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarTercero.setPreferredSize(new java.awt.Dimension(200, 50));
        btnBuscarTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTerceroActionPerformed(evt);
            }
        });

        btnUsuariosActivos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUsuariosActivos.setText("Usuarios activos");
        btnUsuariosActivos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUsuariosActivos.setPreferredSize(new java.awt.Dimension(200, 50));
        btnUsuariosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActivosActionPerformed(evt);
            }
        });

        btnUsuariosEliminados.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUsuariosEliminados.setText("Usuarios eliminados");
        btnUsuariosEliminados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUsuariosEliminados.setPreferredSize(new java.awt.Dimension(200, 50));
        btnUsuariosEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosEliminadosActionPerformed(evt);
            }
        });

        btnEmpleadosRegistrados.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEmpleadosRegistrados.setText("Empleados");
        btnEmpleadosRegistrados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEmpleadosRegistrados.setPreferredSize(new java.awt.Dimension(200, 50));
        btnEmpleadosRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosRegistradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuariosEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmpleadosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpleadosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTerceroActionPerformed
        // TODO add your handling code here:
        rpClientUsers();
    }//GEN-LAST:event_btnBuscarTerceroActionPerformed

    private void btnUsuariosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActivosActionPerformed
        // TODO add your handling code here:
        rpActiveUsers();
    }//GEN-LAST:event_btnUsuariosActivosActionPerformed

    private void btnUsuariosEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosEliminadosActionPerformed
        // TODO add your handling code here:
        rpInactiveUsers();
    }//GEN-LAST:event_btnUsuariosEliminadosActionPerformed

    private void btnEmpleadosRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosRegistradosActionPerformed
        // TODO add your handling code here:
        rpEmployeeUsers();
    }//GEN-LAST:event_btnEmpleadosRegistradosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTercero;
    private javax.swing.JButton btnEmpleadosRegistrados;
    private javax.swing.JButton btnUsuariosActivos;
    private javax.swing.JButton btnUsuariosEliminados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables
}
